#!/bin/bash

display_file() {
	(echo "$1"
	echo "------------------------"
	echo ""
	cat $2)| less

}


n=/tmp/demo-cblk

src=$n"_s"
s1=$n"_1"
s2=$n"_2"
dst=$n"_d"

clean() {
	rm $src $s1 $s2 $dst
} 

trap clean EXIT SIGINT

man man > $src
display_file "file before" $src
key=$(cblk-genkey) 
BS=2
cblk-split if=$src of=$s1 of=$s2 key=$key BS=$BS
display_file "first file of the splitted" $s1
display_file "second file of the splitted" $s2
cblk-regroup if=$s1 if=$s2 key=$key of=$dst BS=$BS
display_file "regrouped file" $dst

